### ISSUE TITLE
NullPointerException from exposeAsEnvironment for container with custom name

### ISSUE THREAD

**Issue by tmccarthy** [avast/docker-compose-gradle-plugin#85]
If a container has a custom name specified with the [`container-name`](https://docs.docker.com/compose/compose-file/#container_name) option, `exposeAsEnvironment()` throws an exception with the following stacktrace:

```
java.lang.NullPointerException: Cannot invoke method endsWith() on null object
        at java_lang_String$endsWith$1.call(Unknown Source)
        at com.avast.gradle.dockercompose.ComposeExtension$_exposeAsEnvironment_closure3$_closure9.doCall(ComposeExtension.groovy:68)
        at com.avast.gradle.dockercompose.ComposeExtension$_exposeAsEnvironment_closure3.doCall(ComposeExtension.groovy:67)
        at com.avast.gradle.dockercompose.ComposeExtension.exposeAsEnvironment(ComposeExtension.groovy:66)
        at com.avast.gradle.dockercompose.ComposeExtension$exposeAsEnvironment$3.call(Unknown Source)
        ...
```

The issue is that the regex at [line 124 of `ComposeUp`](https://github.com/avast/docker-compose-gradle-plugin/blob/0.4.2/src/main/groovy/com/avast/gradle/dockercompose/tasks/ComposeUp.groovy#L124) will not necessarily match a custom container name. This leads to a `null` value of `instanceName`, which eventually causes the exception.

I will submit a pull request fixing this issue momentarily.

**Comment by augi** [comment]
Released as 0.4.3, thanks again!
